#!/usr/bin/env bash

set -euo pipefail

PACKAGE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FIXTURE_DIR="${PACKAGE_ROOT}/Tests/LuxelCoreTests/Fixtures/VoiceDetection"
TEMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TEMP_DIR}"' EXIT

mkdir -p "${FIXTURE_DIR}"

ROWS_URL='https://datasets-server.huggingface.co/rows?dataset=hf-internal-testing%2Flibrispeech_asr_dummy&config=clean&split=validation&offset=0&length=1'
SPEECH_URL="$(curl -fsSL "${ROWS_URL}" | jq -r '.rows[0].row.audio[0].src')"
curl -fsSL "${SPEECH_URL}" -o "${TEMP_DIR}/speech.flac"

ffmpeg -nostdin -loglevel error -y -i "${TEMP_DIR}/speech.flac" \
  -ar 16000 -ac 1 -c:a pcm_s16le "${FIXTURE_DIR}/speech-16k-mono.wav"
ffmpeg -nostdin -loglevel error -y -i "${TEMP_DIR}/speech.flac" -t 0.35 \
  -ar 16000 -ac 1 -c:a pcm_s16le "${FIXTURE_DIR}/short-speech-16k-mono.wav"

python3 - "${FIXTURE_DIR}" <<'PY'
import math
import struct
import sys
import wave
from pathlib import Path

root = Path(sys.argv[1])

def write(name, rate, channels, duration, sample):
    frame_count = round(rate * duration)
    with wave.open(str(root / name), "wb") as output:
        output.setnchannels(channels)
        output.setsampwidth(2)
        output.setframerate(rate)
        frames = bytearray()
        for frame in range(frame_count):
            values = sample(frame, rate, channels)
            for value in values:
                frames.extend(struct.pack("<h", max(-32768, min(32767, round(value * 32767)))))
        output.writeframes(frames)

write("silence-16k-mono.wav", 16000, 1, 3.0, lambda frame, rate, channels: (0.0,))

noise_state = 0x4C555845
def noise():
    global noise_state
    noise_state = (1664525 * noise_state + 1013904223) & 0xFFFFFFFF
    return ((noise_state >> 8) / 0xFFFFFF * 2.0) - 1.0

def room_tone(frame, rate, channels):
    value = noise() * 0.004 + math.sin(2 * math.pi * 60 * frame / rate) * 0.001
    return (value, value * 0.93)
write("room-tone-44100-stereo.wav", 44100, 2, 3.0, room_tone)

def music(frame, rate, channels):
    time = frame / rate
    envelope = min(1.0, time * 5.0, (3.0 - time) * 5.0)
    left = sum(math.sin(2 * math.pi * frequency * time) for frequency in (220, 277.18, 329.63))
    right = sum(math.sin(2 * math.pi * frequency * time + 0.2) for frequency in (220, 277.18, 329.63))
    return (left * 0.025 * envelope, right * 0.025 * envelope)
write("music-48k-stereo.wav", 48000, 2, 3.0, music)

def click(frame, rate, channels):
    offset = frame - rate
    value = 0.0 if offset < 0 or offset >= 160 else 0.8 * math.exp(-offset / 22) * (-1 if offset % 2 else 1)
    return (value,)
write("click-44100-mono.wav", 44100, 1, 3.0, click)

def cough(frame, rate, channels):
    time = frame / rate
    offset = time - 1.0
    if offset < 0 or offset >= 0.28:
        return (0.0,)
    envelope = math.sin(math.pi * offset / 0.28) ** 2
    return ((noise() * 0.32 + math.sin(2 * math.pi * 145 * offset) * 0.08) * envelope,)
write("cough-like-48k-mono.wav", 48000, 1, 3.0, cough)

key_times = (0.55, 0.92, 1.35, 1.78, 2.24)
def keyboard(frame, rate, channels):
    time = frame / rate
    value = 0.0
    for key_time in key_times:
        offset = time - key_time
        if 0 <= offset < 0.018:
            value += noise() * 0.32 * math.exp(-offset * 260)
    return (value, value * 0.88)
write("keyboard-44100-stereo.wav", 44100, 2, 3.0, keyboard)
PY

ffmpeg -nostdin -loglevel error -y \
  -i "${FIXTURE_DIR}/speech-16k-mono.wav" \
  -i "${FIXTURE_DIR}/music-48k-stereo.wav" \
  -filter_complex '[0:a]aresample=48000,pan=stereo|c0=c0|c1=c0,volume=0.9[speech];[1:a]volume=0.12[music];[speech][music]amix=inputs=2:duration=first:normalize=0' \
  -ar 48000 -ac 2 -c:a pcm_s16le "${FIXTURE_DIR}/podcast-like-48k-stereo.wav"

python3 - "${FIXTURE_DIR}" <<'PY'
import hashlib
import json
import sys
import wave
from pathlib import Path

root = Path(sys.argv[1])
metadata = {
    "speech-16k-mono.wav": ("prompt", "LibriSpeech dev-clean 1272-128104-0000", "CC BY 4.0; LibriVox contribution distributed through LibriSpeech"),
    "short-speech-16k-mono.wav": ("noPrompt", "First 350 ms of LibriSpeech 1272-128104-0000", "CC BY 4.0; LibriVox contribution distributed through LibriSpeech"),
    "podcast-like-48k-stereo.wav": ("prompt", "LibriSpeech 1272-128104-0000 mixed with deterministic synthetic music", "Speech is CC BY 4.0; music is generated by this repository"),
    "silence-16k-mono.wav": ("noPrompt", "Deterministic generated zero samples", "Generated by this repository; no person recorded"),
    "room-tone-44100-stereo.wav": ("noPrompt", "Deterministic generated seeded noise and 60 Hz tone", "Generated by this repository; no person recorded"),
    "music-48k-stereo.wav": ("noPrompt", "Deterministic generated three-note harmonic signal", "Generated by this repository; no person recorded"),
    "click-44100-mono.wav": ("noPrompt", "Deterministic generated decaying impulse", "Generated by this repository; no person recorded"),
    "cough-like-48k-mono.wav": ("noPrompt", "Deterministic generated shaped-noise burst", "Generated by this repository; no person recorded"),
    "keyboard-44100-stereo.wav": ("noPrompt", "Deterministic generated transient sequence", "Generated by this repository; no person recorded"),
}

fixtures = []
for name, (expected, provenance, consent_license) in metadata.items():
    path = root / name
    with wave.open(str(path), "rb") as audio:
        frames = audio.getnframes()
        rate = audio.getframerate()
        fixtures.append({
            "file": name,
            "expected": expected,
            "provenance": provenance,
            "consentLicense": consent_license,
            "durationSeconds": frames / rate,
            "sampleRate": rate,
            "channels": audio.getnchannels(),
            "bitsPerSample": audio.getsampwidth() * 8,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        })

manifest = {
    "schemaVersion": 1,
    "speechSource": {
        "dataset": "LibriSpeech ASR dummy / LibriSpeech dev-clean",
        "recordingID": "1272-128104-0000",
        "sourceIndex": 0,
        "sourceRowsURL": "https://datasets-server.huggingface.co/rows?dataset=hf-internal-testing%2Flibrispeech_asr_dummy&config=clean&split=validation&offset=0&length=1",
        "datasetURL": "https://www.openslr.org/12",
        "license": "CC BY 4.0",
        "transcript": "MISTER QUILTER IS THE APOSTLE OF THE MIDDLE CLASSES AND WE ARE GLAD TO WELCOME HIS GOSPEL",
    },
    "fixtures": fixtures,
}
(root / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
PY

echo "Generated voice detection fixtures in ${FIXTURE_DIR}"
